quiz/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('',include('quizportal.urls')),
    path('admin/', admin.site.urls),
]

quizportal/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView
from django.conf.urls.static import static


urlpatterns = [
	# Quiz
    path('', LoginView.as_view(template_name='quizportal/login.html'), name="login"),
    path('detail/Section/<section_no>/<id_no>', views.detail, name='detail'),
    path('score/Section/<section_no>/<id_no>', views.score, name='score'),
    path('ended', views.ended, name='ended'),
    path('endSection/<section_no>', views.endSection, name='endSection'),
    # path('register', views.register, name='register'),
    path('admincsvupload/<section_no>', views.csvupload, name='csvupload'),
    path('admintimeupload/<section_no>', views.timeupload, name='timeupload'),
    path('adminmain', views.adminmain, name='adminmain'),
    path('DownloadUserData', views.DownloadUserData, name='DownloadUserData'),
    path('adminall', views.adminall, name='adminall'),
    path('regis', views.regis, name='regis'),
    path('admindelete/<nu>', views.admindelete, name='admindelete'),
    path('logout', LogoutView.as_view(template_name='quizportal/logout.html'), name="logout"),

]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quizportal/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import now
from django.contrib.postgres.fields import ArrayField

#Questions
class Section1(models.Model):
	ANSWER_CHOICES=(
		("A", ("A")),
		("B", ("B")),
		("C", ("C")),
		("D", ("D")),
		)
	id_no=models.CharField(max_length=1000,primary_key=True)
	question=models.TextField()
	image=models.ImageField(upload_to='pictures', blank=True)
	optionA=models.TextField()
	optionB=models.TextField()
	optionC=models.TextField()
	optionD=models.TextField()
	correct_choice=models.CharField(choices=ANSWER_CHOICES, max_length=10, null=False)

#Questions
class Section2(models.Model):
	ANSWER_CHOICES=(
		("A", ("A")),
		("B", ("B")),
		("C", ("C")),
		("D", ("D")),
		)
	id_no=models.CharField(max_length=1000,primary_key=True)
	question=models.TextField()
	image=models.ImageField(upload_to='pictures', blank=True)
	optionA=models.TextField()
	optionB=models.TextField()
	optionC=models.TextField()
	optionD=models.TextField()
	correct_choice=models.CharField(choices=ANSWER_CHOICES, max_length=10, null=False)

#Questions
class Section3(models.Model):
	ANSWER_CHOICES=(
		("A", ("A")),
		("B", ("B")),
		("C", ("C")),
		("D", ("D")),
		)
	id_no=models.CharField(max_length=1000,primary_key=True)
	question=models.TextField()
	image=models.ImageField(upload_to='pictures', blank=True)
	optionA=models.TextField()
	optionB=models.TextField()
	optionC=models.TextField()
	optionD=models.TextField()
	correct_choice=models.CharField(choices=ANSWER_CHOICES, max_length=10, null=False)


#Time Interval Of Quiz
class Time1(models.Model):
	id_no=models.OneToOneField(User, on_delete=models.CASCADE,null=True)
	start_time = models.DateTimeField(max_length=100, blank=False, default=now)
	end_time = models.DateTimeField(max_length=100, blank=False, default=now)

	def __str__(self):
		return str(self.end_time)

#Time Interval Of Quiz
class Time2(models.Model):
	id_no=models.OneToOneField(User, on_delete=models.CASCADE,null=True)
	start_time = models.DateTimeField(max_length=100, blank=False, default=now)
	end_time = models.DateTimeField(max_length=100, blank=False, default=now)

	def __str__(self):
		return str(self.end_time)

#Time Interval Of Quiz
class Time3(models.Model):
	id_no=models.OneToOneField(User, on_delete=models.CASCADE,null=True)
	start_time = models.DateTimeField(max_length=100, blank=False, default=now)
	end_time = models.DateTimeField(max_length=100, blank=False, default=now)

	def __str__(self):
		return str(self.end_time)

		
'''#Scored Card + Solved
class SolvedQ1(models.Model):
	id_no=models.ForeignKey(User, on_delete=models.CASCADE)
	q_idsol=ArrayField(models.IntegerField(), default=list)
	q_idunsol=ArrayField(models.IntegerField(), default=list)

#Scored Card + Solved
class SolvedQ2(models.Model):
	id_no=models.ForeignKey(User, on_delete=models.CASCADE)
	q_idsol=ArrayField(models.IntegerField(), default=list)
	q_idunsol=ArrayField(models.IntegerField(), default=list)

#Scored Card + Solved
class SolvedQ3(models.Model):
	id_no=models.ForeignKey(User, on_delete=models.CASCADE)
	q_idsol=ArrayField(models.IntegerField(), default=list)
	q_idunsol=ArrayField(models.IntegerField(), default=list)'''


class SolvedQ1(models.Model):
	id_no=models.ForeignKey(User, on_delete=models.CASCADE)
	q_id=models.ForeignKey(Section1, on_delete=models.CASCADE)
	check=models.BooleanField(default=False)
	
class SolvedQ2(models.Model):
	id_no=models.ForeignKey(User, on_delete=models.CASCADE)
	q_id=models.ForeignKey(Section2, on_delete=models.CASCADE)
	check=models.BooleanField(default=False)
	
class SolvedQ3(models.Model):
	id_no=models.ForeignKey(User, on_delete=models.CASCADE)
	q_id=models.ForeignKey(Section3, on_delete=models.CASCADE)
	check=models.BooleanField(default=False)

class Time(models.Model):
	s_no=models.PositiveIntegerField()
	time=models.TimeField()
	

quizportal/views.py
from django.shortcuts import render,redirect
from django.template import loader
from django import forms
from django.urls import reverse
from django.http import HttpResponse,HttpResponseRedirect
from .models import *
from .forms import *
from django.contrib.auth.forms import UserChangeForm, UserCreationForm, AuthenticationForm
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from datetime import timedelta
from django.utils import timezone


# #Registration
# def register(request):
# 	if(request.method=="POST"):
# 		form=RegistrationForm(request.POST)
# 		if(form.is_valid()):
# 			form.save()
# 			return HttpResponseRedirect('/')  #Back To Login Form
# 	else:
# 		form=RegistrationForm()
# 	return render(request,'quizportal/register.html',{'form':form})


#Questions rendering
@login_required(login_url='login')
def detail(request, section_no, id_no):
	print(section_no, id_no, request)
	#Check if logged in user is Admin
	if(request.user.username=='admin'):
		return HttpResponseRedirect('/adminmain')

	else:
		
		#Setting time to user given time in minutes from the login to that section , time

		if(section_no =='1' and len(Time1.objects.filter(Q(id_no=request.user)))==0 and id_no=='1' and len(Section1.objects.all())>0):
			start=timezone.now()
			timeobj=Time.objects.filter(Q(s_no=1))
			for timeob in timeobj:
				end=timeob.time
				break
			end=str(end).split(":")
			end=end[1]

			obj,notif=Time1.objects.get_or_create(id_no=request.user, start_time=start, end_time=start+timedelta(minutes=(int)(end)))
			if notif is True:
				obj.save()

		elif(section_no=='2' and len(Time2.objects.filter(Q(id_no=request.user)))==0 and id_no=='1' and len(Section2.objects.all())>0):
			time=Time1.objects.filter(Q(id_no=request.user))
			if(len(time)>0):
				for i in time:
					endtime=i.end_time
					break
			if(endtime<timezone.now()):
				start=timezone.now()
				timeobj=Time.objects.filter(Q(s_no=2))
				for timeob in timeobj:
					end=timeob.time
					break
				end=str(end).split(":")
				end=end[1]

				obj,notif=Time2.objects.get_or_create(id_no=request.user,start_time=start, end_time=start+timedelta(minutes=(int)(end)))
				if notif is True:
					obj.save()

		elif(section_no=='3' and len(Time3.objects.filter(Q(id_no=request.user)))==0 and id_no=='1' and len(Section3.objects.all())>0):
			#print("3")
			time=Time1.objects.filter(Q(id_no=request.user))
			time1=Time2.objects.filter(Q(id_no=request.user))
			if(len(time)>0):
				for i in time:
					endtime=i.end_time
					break
			if(len(time1)>0):
				for i in time1:
					endtime1=i.end_time
					break
			if(endtime<timezone.now() and endtime1<timezone.now()):
				start=timezone.now()
				timeobj=Time.objects.filter(Q(s_no=3))
				for timeob in timeobj:
					end=timeob.time
					break
				end=str(end).split(":")
				end=end[1]
				obj,notif=Time3.objects.get_or_create(id_no=request.user,start_time=start, end_time=start+timedelta(minutes=(int)(end)))
				if notif is True:
					obj.save()
		#Quiz Ended
		if(section_no=='1'):
			time=Time1.objects.filter(Q(id_no=request.user))
		elif(section_no=='2'):
			time=Time2.objects.filter(Q(id_no=request.user))
		else:
			time=Time3.objects.filter(Q(id_no=request.user))
		#print(time)

		if(len(time)>0):
			for i in time:
				endtime=i.end_time
				break
			#Time Conversion according to 24hrs clock
			f=(endtime)
			f=str(f).split(" ")
			time=f[1]
			time=str(time).split(":")
			h=str(((int)(time[0])))
			m=str(((int)(time[1])))

		else:
			endtime=""

		if(len(time)<0 and endtime < timezone.now()):
			return HttpResponseRedirect('/ended')


		#Trying to access Section 2 before time
		if(section_no=='2'):
			time2=Time1.objects.filter(Q(id_no=request.user))
			if(len(time2)>0):
				for i in time2:
					endtime=i.end_time
					break
			#print(endtime, timezone.now())
			if(endtime > timezone.now()):
				return HttpResponseRedirect('/detail/Section/1/1')

		#Trying to access Section 3 before time
		elif(section_no=='3'):
			time3=Time1.objects.filter(Q(id_no=request.user))
			if(len(time3)>0):
				for i in time3:
					endtime=i.end_time
					break
			#print(endtime, timezone.now())
			if(endtime > timezone.now()):
				return HttpResponseRedirect('/detail/Section/1/1')

			time2=Time2.objects.filter(Q(id_no=request.user))
			if(len(time2)>0):
				for i in time2:
					endtime=i.end_time
					break
			if(endtime > timezone.now()):
				if(len(Section2.objects.all())>0):
					return HttpResponseRedirect('/detail/Section/2/1')


		
		#POST request
		if(request.method=='POST'):
			id1=(int)(id_no)
			id1=id1-1
			
			if(section_no=='1'):
				question=Section1.objects.filter(id_no=str(id_no))
				question1=Section1.objects.filter(id_no=str(id1))
				p1=SolvedQ1.objects.filter(Q(q_id=question1.get(id_no=id1)) ,Q(id_no=request.user), Q(check=False))
			
			elif(section_no=='2'):
				question=Section2.objects.filter(id_no=str(id_no))
				question1=Section2.objects.filter(id_no=str(id1))
				p1=SolvedQ2.objects.filter(Q(q_id=question1.get(id_no=id1)) ,Q(id_no=request.user), Q(check=False))
			
			elif(section_no=='3'):
				question=Section3.objects.filter(id_no=str(id_no))
				question1=Section3.objects.filter(id_no=str(id1))
				p1=SolvedQ3.objects.filter(Q(q_id=question1.get(id_no=id1)) ,Q(id_no=request.user), Q(check=False))


			#Choices
			for i in question1:
				correct_choice1=i.correct_choice
				if(len(p1)==0 and correct_choice1==request.POST.get('choice')):
					if(section_no=='1'):
						obj,notif=SolvedQ1.objects.get_or_create(id_no=request.user, q_id=question1.get(id_no=id1), check=True)
					elif(section_no=='2'):
						obj,notif=SolvedQ2.objects.get_or_create(id_no=request.user, q_id=question1.get(id_no=id1), check=True)
					elif(section_no=='3'):
						obj,notif=SolvedQ3.objects.get_or_create(id_no=request.user, q_id=question1.get(id_no=id1), check=True)
						
					if notif is True:
						obj.save()

				else:
					if(len(p1)==0 and correct_choice1!=request.POST.get('choice')):
						if(section_no=='1'):
							obj,notif=SolvedQ1.objects.get_or_create(id_no=request.user, q_id=question1.get(id_no=id1), check=False)
						elif(section_no=='2'):
							obj,notif=SolvedQ2.objects.get_or_create(id_no=request.user, q_id=question1.get(id_no=id1), check=False)
						else:
							obj,notif=SolvedQ3.objects.get_or_create(id_no=request.user, q_id=question1.get(id_no=id1), check=False)
								
						if notif is True:
							obj.save()

			if(len(question)>0):
				args={}
				for i in question:
					if(i.image):
						#Image.open('http://127.0.0.1:8000/media/'+str(i.image))
						args={'question':question, 'section_no':section_no, 'timer':h+":"+m+":"+time[2].split("+")[0], 'image1':"image"}
					else:
						args={'question':question, 'section_no':section_no, 'timer':h+":"+m+":"+time[2].split("+")[0]}
					break
				return render(request, 'quizportal/questions.html', args)

			else:
				if(len(SolvedQ1.objects.filter(Q(id_no=request.user))) < len(Section1.objects.all())):
					return HttpResponseRedirect('/detail/Section/1/'+str(int(id_no)+1))
				elif(len(SolvedQ2.objects.filter(Q(id_no=request.user)))< len(Section2.objects.all()) and section_no=='1'):
					markSection1End(request)
					return HttpResponseRedirect('/detail/Section/2/1')
				elif(len(SolvedQ2.objects.filter(Q(id_no=request.user)))< len(Section2.objects.all()) and section_no=='2'):
					return HttpResponseRedirect('/detail/Section/2/'+str(int(id_no)+1))
				elif(len(SolvedQ3.objects.filter(Q(id_no=request.user)))< len(Section3.objects.all()) and section_no=='2'):
					markSection2End(request)
					return HttpResponseRedirect('/detail/Section/3/1')
				elif(len(SolvedQ3.objects.filter(Q(id_no=request.user)))< len(Section3.objects.all()) and section_no=='3'):
					return HttpResponseRedirect('/detail/Section/2/'+str(int(id_no)+1))
				else:
					return HttpResponseRedirect('/ended')


		#GET request
		else:
			
			#Check if its the last Question for Section 1
			if(section_no=='1'):
				question=Section1.objects.all()
				if(len(question)==0):
					markSection1End(request)
					if(len(Section2.objects.all())>0):
						return HttpResponseRedirect('/detail/Section/2/1')
					else:
						return HttpResponseRedirect('/ended')
			
			#Check if its the last Question for Section 2
			elif(section_no=='2'):
				question=Section2.objects.all()
				if(len(question)==0):
					markSection2End(request)
					if(len(Section3.objects.all())>0):
						return HttpResponseRedirect('/detail/Section/3/1')
					else:
						return HttpResponseRedirect('/ended')
			
			#Check if its the last Question for Section 3
			elif(section_no=='3'):
				question=Section3.objects.all()
				if(len(question)==0):
					markSection3End(request)
					return HttpResponseRedirect('/ended')



			#If its the last Question for the particular Section
			id1=(int)(id_no)

			#Section 1
			if(section_no=='1'):
				question1=Section1.objects.filter(id_no=str(id1))
				if(len(question1)==0):
					#print("yes")
					markSection1End(request)
					return HttpResponseRedirect('/detail/Section/2/1')
				else:
					#Attempted Questions
					if(len(SolvedQ1.objects.filter(Q(q_id=question1.get(id_no=id1)) ,Q(id_no=request.user)))>0):
						score=SolvedQ1.objects.filter(Q(id_no=request.user))
						return render(request, 'quizportal/attempted.html', {'section_no':section_no, 'id_no':id1})
					else:
						#Unattempted
						question=Section1.objects.filter(Q(id_no__exact=str(id_no)))
						args={}
						for i in question:
							if(i.image):
								#Image.open('http://127.0.0.1:8000/media/'+str(i.image))
								args={'question':question, 'section_no':section_no, 'timer':h+":"+m+":"+time[2].split("+")[0], 'image1':"image"}
							else:
								args={'question':question, 'section_no':section_no, 'timer':h+":"+m+":"+time[2].split("+")[0]}
							break

quizportal/templates/quizportal/adminall.html
{% extends 'adminbase.html' %}
{% block body %}
<div class="container" style="justify-content:center; margin-top:10%;">
	<div class="container text-center">
		<div class="container text-center">
			<div class="page-header">
				<h1><b>Details Of All Users</b></h1>
			</div>
			<br><br>
			<table class="table table-bordered table-dark">
				<thead>
					<tr>
						<th scope="col">#</th>
						<th scope="col">Enrollment Number</th>
						<th scope="col">Name</th>
						<th scope="col">Section1 Score</th>
						<th scope="col">Section2 Score</th>
						<th scope="col">Section3 Score</th>
					</tr>
				</thead>
				<tbody>
					{% for i,j in allusers.items %}
					<tr>
						<td><b>{{ forloop.counter }}</b></th>
							<td><b>{{i}}</b></td>
							{% for k in j %}
							<td><b>{{k}}</b></td>
							{% endfor %}
						</tr>
						{% endfor %}
					</tbody>
				</table>

				<br>
			</div>
			<div class="container">
				<a href="{% url 'DownloadUserData' %}"><button class="btn btn-default">
						<b>Download File</b>
					</button></a>
			</div>
			<br>
			<b>
				<div class="text-center p-t-40" style="font-size: 20px;">
					Developer :- Abhinav Sharma
					<a href="https://www.facebook.com/abhinav.sharma.16906" class="fa fa-facebook"></a>
				</div>
			</b>
		</div>
	</div>
	{% endblock %}

quizportal/templates/quizportal/adminmain.html
{% extends 'adminbase.html' %}
{% block body %}
<div class="container" style="justify-content:center; margin-top:10%;">
	<div class="container text-center">
		<div class="container text-center">
			<div class="page-header">
				<h1><b>Hello Admin</b></h1>
			</div>
			<br><br>
			<div class="container">
				<a href="/adminall">
					<button class="btn btn-default" style='margin-right:16px'>
						<b>Score Of All Users</b>
					</button>
				</a>
				<a href="/regis">
					<button class="btn btn-default" style='margin-left:16px'>
						<b>Register Users Manually</b>
					</button>
				</a>
			</div>
			<br>
		</div>
	</div>
</div>
<div class="col-xs-15">
	<table class="table table-bordered table-dark table-condensed" align="center">
		<thead>
			<tr>
				<th scope="col">S No.</th>
				<th scope="col">Section Questions(CSV File)</th>
				<th scope="col">Timely Division</th>
				<th scope="col">Delete Questions</th>
				<th scope="col">Delete Time of User</th>
				<th scope="col">Delete Sec. End Time</th>
				<th scope="col">Delete Solved Users</th>
			</tr>
		</thead>
		<tbody>

			<!-- Section 1 -->
			<tr>
				<td align="center">1</td>
				<td align="center">
					<a href="/admincsvupload/1"><button class="btn btn-default">
						<b>Section 1</b>
					</button></a>
				</td>
				<td align="center">
					<a href="/admintimeupload/1"><button class="btn btn-default">
						<b>Section 1</b>
					</button></a>
				</td>
				<td align="center">
					<button onclick="myFunction(2)" class="btn btn-default">
						<b>Section 1</b>
					</button>
				</td>
				<td align="center">
					<button onclick="myFunction(5)" class="btn btn-default">
						<b>Section 1</b>
					</button>
				</td>
				<td rowspan="3" align="center">
					<button onclick="myFunction(8)" class="btn btn-default">
						<b>All Sections</b>
					</button>
				</td>
				<td align="center">
					<button onclick="myFunction(9)" class="btn btn-default">
						<b>Sections 1</b>
					</button>
				</td>
			</tr>

			<!-- Section 2 -->
			<tr>
				<td align="center">2</td>
				<td align="center">
					<a href="/admincsvupload/2"><button class="btn btn-default">
						<b>Section 2</b>
					</button></a>
				</td>
				<td align="center">
					<a href="/admintimeupload/2"><button class="btn btn-default">
						<b>Section 2</b>
					</button></a>
				</td>
				<td align="center">
					<button onclick="myFunction(3)" class="btn btn-default">
						<b>Section 2</b>
					</button>
				</td>
				<td align="center">
					<button onclick="myFunction(6)" class="btn btn-default">
						<b>Section 2</b>
					</button>
				</td>
				<td align="center">
					<button onclick="myFunction(10)" class="btn btn-default">
						<b>Sections 2</b>
					</button>
				</td>
			</tr>

			<!-- Section 3 -->
			<tr>
				<td align="center">3</td>
				<td align="center">
					<a href="/admincsvupload/3"><button class="btn btn-default">
						<b>Section 3</b>
					</button></a>
				</td>
				<td align="center">
					<a href="/admintimeupload/3"><button class="btn btn-default">
						<b>Section 3</b>
					</button></a>
				</td>
				<td align="center">
					<button onclick="myFunction(4)"" class="btn btn-default">
						<b>Section 3</b>
					</button>
				</td>
				<td align="center">
					<button onclick="myFunction(7)" class="btn btn-default">
						<b>Section 3</b>
					</button>
				</td>
				<td align="center">
					<button onclick="myFunction(11)" class="btn btn-default">
						<b>Sections 3</b>
					</button>
				</td>
			</tr>
		</tbody>
	</table>
</div>

<br>
<div class="container">
	<a href="/logout"><button class="button">
		<b>Logout</b>
	</button></a>
</div>

<br>
<b>
	<div class="text-center p-t-40" style="font-size: 20px;">
		Developer :- Abhinav Sharma
		<a href="https://www.facebook.com/abhinav.sharma.16906" class="fa fa-facebook"></a>
	</div>
</b>
<script type="text/javascript">

	function myFunction(event)
	{
		console.log("hi");
		if(confirm("Are You Sure You Want To Delete It!! Your Data Will Be Permanently Lost"))
		{
			window.location.href="/admindelete/"+String(event);
		}
		
	}
	message="{{message}}"
	console.log(message)
	if(message.length > 0)
	{
		alert("Successfully Deleted");
		window.location.href="/adminmain";
	}

	
</script>
{% endblock %}

quizportal/templates/quizportal/attempted.html
{% extends 'base1.html' %}
{% block body %}
<div class="container" style="justify-content:center; margin-top:10%;">
	<div class="container text-center">
		<div class="container text-center">
			<h1><b>You have already attempted this question</b></h1>
		</div>
		<br><br>
		<div class="container text-center">
			<a href="/score/Section/{{section_no}}/{{id_no}}"><button class="btn btn-default">
					<b>Your Score</b>
				</button></a>
		</div>
		<footer>
			<b>
				<div class="text-center p-t-40" style="font-size: 15px;">
					Developer :- Abhinav Sharma
				</div>
			</b>
		</footer>
		{% endblock %}

quizportal/templates/quizportal/ended.html
{% extends 'base1.html' %}
{% block body %}
<div class="container" style="justify-content:center; margin-top:10%;">
	<div class="container text-center">
		<div class="container text-center">
			<div class="page-header">
				<h1><b>Quiz Has Ended</b></h1>
			</div>
			<br><br>
			{% for i in id %}
			<div class="page-header">
				<h2><b>{{i.username}} Your Final Scores Are:- </b></h2>
			</div>
			</div>
			<table class="table table-bordered table-dark">
				<thead>
					<tr>
						<th scope="col">Section Number#</th>
						<th scope="col">Scores</th>
					</tr>
				{% endfor %}
				</thead>
				<tbody>
					{% for i in scores %}
					<tr>
						<td>{{ forloop.counter }}</td>
						<td>{{i}}</td>
					</tr>
					{% endfor %}
				</tbody>
			</table>

			<br><br>
			<div class="container">
				<h5><b>Thanks For Giving The Quiz</b></h5>
			</div>
			<br>
			<div class="container">
				<a href="/logout"><button class="btn btn-default">
						<b>Logout</b>
					</button></a>
			</div>
		</div>
		</div>
		<br><br><br><br><br>
		<b>
			<div class="text-center p-t-40" style="font-size: 15px;">
				Developer :- Abhinav Sharma
				<a href="https://www.facebook.com/abhinav.sharma.16906" class="fa fa-facebook"></a>
			</div>
		</b>
{% endblock %}

quizportal/templates/quizportal/logout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body %}
<div class="page-header">
	<h1>Login</h1>
</div>
<div class="col-lg-5">
	<form method="POST" action="">
		{% csrf_token %}
</div>
</form>
{% endblock %}

quizportal/templates/quizportal/timeupload.html
{% load crispy_forms_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<title>Upload Questions</title>
	<SCRIPT type="text/javascript">
		function preventBack() { window.history.forward(); }
		setTimeout("preventBack()", 0);
		window.onunload = function () { null };
	</SCRIPT>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!--===============================================================================================-->
	<link rel="icon" type="image/png" href={% static 'quizportal/images/icons/favicon.ico' %} />
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href={% static 'quizportal/vendor/bootstrap/css/bootstrap.min.css' %}>
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css"
		href={% static 'quizportal/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}>
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css"
		href={% static 'quizportal/fonts/iconic/css/material-design-iconic-font.min.css' %}>
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href={% static 'quizportal/vendor/animate/animate.css' %}>
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href={% static 'quizportal/vendor/css-hamburgers/hamburgers.min.css' %}>
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href={% static 'quizportal/vendor/animsition/css/animsition.min.css' %}>
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href={% static 'quizportal/vendor/select2/select2.min.css' %}>
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href={% static 'quizportal/vendor/daterangepicker/daterangepicker.css' %}>
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href={% static 'quizportal/css/util.css' %}>
	<link rel="stylesheet" type="text/css" href={% static 'quizportal/css/main.css' %}>
	<!--===============================================================================================-->
</head>

<body>
	<div class="limiter">
		<div class="container-login100" style="background-image: url('static/quizportal/images/bg-01.jpg');">
			<div class="wrap-login100">
				<form method="POST" action="">
					{% csrf_token %}
					<span class="login100-form-logo">
						<i class="zmdi zmdi-landscape"></i>
					</span>

					<span class="login100-form-title p-b-34 p-t-27">
						<b>Hello ADMIN</b><br><br>
						Time For <b>Section {{section_no}}</b>
					</span>

					<div class="container">
						<input type="text" name="time" class="timeinput form-control" required="" id="id_time" placeholder="Time In Format - HH:MM:SS">
						<br>
					</div>

					<div class="container-login100-form-btn">
						<button class="login100-form-btn">
							<b>Update Time</b>
						</button>
					</div>
					<br>
					<b>
						<div class="text-center p-t-40" style="font-size: 15px;">
							Developer :- Abhinav Sharma
							<a href="https://www.facebook.com/abhinav.sharma.16906" class="fa fa-facebook"></a>
						</div>
					</b>
				</form>
			</div>
		</div>
	</div>
</body>

</html>